/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package students_rec;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MEGAMAN
 */
public final class Student_Form extends javax.swing.JFrame {

    Student_CRUD studData = new Student_CRUD();

    /**
     * Creates new form Student_Form
     */
    public Student_Form() {
        initComponents();
        disabling();
        resetFields();
    }

    DefaultTableModel model;
    private int increament = 0;
    int id = -1;
    String tempName = "";
    String gndr = "";

    void disabling() {
        //عشان يقفل ازرار التعديل والاضافة والحذف
        add_btn.setEnabled(false);
        delete_btn.setEnabled(false);
        update_btn.setEnabled(false);
    }

    void resetFields() {

        //عشان يصفر الخانات حق الادخال
        name_fld.setText("");
        age_fld.setText("");
        class_fld.setSelectedIndex(-1);
        phone_fld.setText("");
        gender_fld.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        student_info_tbl = new javax.swing.JTable();
        add_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        refresh_btn = new javax.swing.JButton();
        dataForm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name_fld = new javax.swing.JTextField();
        age_fld = new javax.swing.JTextField();
        phone_fld = new javax.swing.JTextField();
        class_fld = new javax.swing.JComboBox<>();
        gender_fld = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        student_info_tbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        student_info_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الجنس", "الصف", "رقم الهاتف", "العمر", "الاسم", "الرقم"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        student_info_tbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        student_info_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                student_info_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(student_info_tbl);
        if (student_info_tbl.getColumnModel().getColumnCount() > 0) {
            student_info_tbl.getColumnModel().getColumn(0).setResizable(false);
            student_info_tbl.getColumnModel().getColumn(2).setResizable(false);
            student_info_tbl.getColumnModel().getColumn(3).setResizable(false);
            student_info_tbl.getColumnModel().getColumn(3).setPreferredWidth(2);
            student_info_tbl.getColumnModel().getColumn(4).setPreferredWidth(150);
            student_info_tbl.getColumnModel().getColumn(5).setResizable(false);
            student_info_tbl.getColumnModel().getColumn(5).setPreferredWidth(1);
        }

        add_btn.setText("اضافة");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        delete_btn.setText("حذف");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        update_btn.setText("تعديل");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        refresh_btn.setText("تحديث القائمة");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });

        dataForm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("الاسم :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("العمر :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("رقم الهاتف :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("الصف :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("الجنس :");

        name_fld.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        name_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_fldActionPerformed(evt);
            }
        });
        name_fld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                name_fldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name_fldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                name_fldKeyTyped(evt);
            }
        });

        age_fld.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        age_fld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                age_fldKeyTyped(evt);
            }
        });

        phone_fld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phone_fldKeyTyped(evt);
            }
        });

        class_fld.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        class_fld.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "الأول", "الثاني", "الثالث", "الرابع", "الخامس", "السادس", "السابع", "الثامن", "التاسع", "أول ثانوي", "ثاني ثانوي", "ثالث ثانوي" }));
        class_fld.setSelectedIndex(-1);

        gender_fld.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gender_fld.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ذكر", "انثى", " " }));
        gender_fld.setSelectedIndex(-1);

        javax.swing.GroupLayout dataFormLayout = new javax.swing.GroupLayout(dataForm);
        dataForm.setLayout(dataFormLayout);
        dataFormLayout.setHorizontalGroup(
            dataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataFormLayout.createSequentialGroup()
                        .addComponent(name_fld)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataFormLayout.createSequentialGroup()
                        .addComponent(age_fld)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataFormLayout.createSequentialGroup()
                        .addComponent(phone_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataFormLayout.createSequentialGroup()
                        .addComponent(gender_fld, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataFormLayout.createSequentialGroup()
                        .addComponent(class_fld, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        dataFormLayout.setVerticalGroup(
            dataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(age_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(phone_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(class_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(gender_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(add_btn)
                        .addGap(18, 18, 18)
                        .addComponent(delete_btn)
                        .addGap(18, 18, 18)
                        .addComponent(update_btn)
                        .addGap(18, 18, 18)
                        .addComponent(refresh_btn))
                    .addComponent(dataForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dataForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_btn)
                            .addComponent(delete_btn)
                            .addComponent(update_btn)
                            .addComponent(refresh_btn)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("نظام مدرستي التجريبي");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
//        if (name_fld.getText().equals("") || age_fld.getText().equals("") || phone_fld.getText().equals("") || class_fld.getText().equals("") || gender_fld.getSelectedIndex() != -1) {
//            System.out.println("enter the missing feilds plz");
//        } else {
        if (name_fld.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "يرجى ادخال الاسم");
            name_fld.requestFocus();
        } else if (age_fld.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "يرجى ادخال العمر");
            age_fld.requestFocus();
        } else if (phone_fld.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "يرجى ادخال رقم الهاتف");
            phone_fld.requestFocus();
        } else if (class_fld.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "يرجى ادخال الصف");
            class_fld.requestFocus();
        } else if (class_fld.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "يرجى تحديد الجنس");
            class_fld.requestFocus();
        } else {
            studData.addNew(name_fld.getText(), age_fld.getText(), phone_fld.getText(), class_fld.getSelectedItem().toString(), gender_fld.getSelectedItem().toString());
            readDatafromLinkedList();
            resetFields();
        }

//        }
    }//GEN-LAST:event_add_btnActionPerformed

    private void name_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_fldActionPerformed

    }//GEN-LAST:event_name_fldActionPerformed

    private void name_fldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_fldKeyTyped
        if (name_fld.getText().isEmpty()) {
            add_btn.setEnabled(false);//عشان نتاكد اذا مافي بيانات في الحقل عشان نقفل الزر
        } else {
            add_btn.setEnabled(true);//عشان نتاكد اذا في بيانات في الحقل عشان نشغل الزر حق الاضافة
        }
        char input = evt.getKeyChar();
        if (!(input < '0' || input > '9') && input != '\b') {//عشان نتاكد انو يكتب حروف فقط في الاسم
            evt.consume();
            JOptionPane.showMessageDialog(this, "لايجب ان يحتوي الاسم على ارقام !");
        }


    }//GEN-LAST:event_name_fldKeyTyped

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        studData.displayAll_To_Console();//بس عشان نتاك ان البيانات بتختزن في اللنكد لست
        readDatafromLinkedList();
    }//GEN-LAST:event_refresh_btnActionPerformed

    private void student_info_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_student_info_tblMouseClicked

        model = (DefaultTableModel) student_info_tbl.getModel();
        int selected = student_info_tbl.getSelectedRow();
        int ID = (int) model.getValueAt(selected, 5);
        String name = model.getValueAt(selected, 4).toString();
        name_fld.setText(name);
        String age = model.getValueAt(selected, 3).toString();
        age_fld.setText(age);
        String phone = model.getValueAt(selected, 2).toString();
        phone_fld.setText(phone);
        String level = model.getValueAt(selected, 1).toString();
        class_fld.setSelectedItem(level);
        String gender = model.getValueAt(selected, 0).toString();
        gender_fld.setSelectedItem(gender);

        //just to make the app beauty !
        delete_btn.setEnabled(true);
        update_btn.setEnabled(true);
        id = ID;
        tempName = name;
        gndr = gender;
    }//GEN-LAST:event_student_info_tblMouseClicked

    private void age_fldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age_fldKeyTyped
        char input = evt.getKeyChar();
        if ((input < '0' || input > '9') && input != '\b') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "يرجى ادخال ارقام فقط!");
        }
    }//GEN-LAST:event_age_fldKeyTyped

    private void phone_fldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_fldKeyTyped
        char input = evt.getKeyChar();
        if ((input < '0' || input > '9') && input != '\b') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "يرجى ادخال ارقام فقط!");
        }
    }//GEN-LAST:event_phone_fldKeyTyped

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed

        System.out.println(id + " was selected");
        studData.delete(id);
        readDatafromLinkedList();
        if (gndr.equals("ذكر")) {
            JOptionPane.showMessageDialog(this, "تم حذف الطالب " + "\t" + "(" + tempName + ")");
        } else {
            JOptionPane.showMessageDialog(this, "تم حذف الطالبه " + "\t" + "(" + tempName + ")");
        }
        id = -1;
        tempName = "";
        gndr = "";
        resetFields();
    }//GEN-LAST:event_delete_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        studData.update(id, name_fld.getText(), age_fld.getText(), phone_fld.getText(), class_fld.getSelectedItem().toString(), gender_fld.getSelectedItem().toString());
        readDatafromLinkedList();
        JOptionPane.showMessageDialog(this, "تم تعديل البيانات بنجاح");
        resetFields();
    }//GEN-LAST:event_update_btnActionPerformed

    private void name_fldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_fldKeyReleased

    }//GEN-LAST:event_name_fldKeyReleased

    private void name_fldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_fldKeyPressed

    }//GEN-LAST:event_name_fldKeyPressed
    private void readDatafromLinkedList() {
        increament = 0;
        try {
            int id = 0;
            model = (DefaultTableModel) student_info_tbl.getModel();

            for (Student_Data looper : studData.stuData) {
                int index = studData.stuData.indexOf(looper);
                String name = looper.getName();
                String age = looper.getAge();
                String phone = looper.getPhone();
                String lvl = looper.getLevel();
                String gender = looper.getGender();
                model.setRowCount(increament);
                model.addRow(new Object[]{gender, lvl, phone, age, name, index});
                increament++;
            }
        } catch (Exception e) {
            System.out.println("reading error = " + e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField age_fld;
    private javax.swing.JComboBox<String> class_fld;
    private javax.swing.JPanel dataForm;
    private javax.swing.JButton delete_btn;
    private javax.swing.JComboBox<String> gender_fld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name_fld;
    private javax.swing.JTextField phone_fld;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JTable student_info_tbl;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
